version: "3.7"

services:
  dc-playwright:
    container_name: dc-playwright
    hostname: dc-playwright.local
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    networks:
      dc-playwright-net:

networks:
  dc-playwright-net:
